### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by jzeferino** [jzeferino/ResxConverter#11]

**Comment by jzeferino** [comment]
@luisgoncalves Does a logo make sensor for you? To use in the nuget/readme?

Liked [this](http://www.flaticon.com/free-icon/catalytic-converter_271924#term=convertion&page;=1&position;=3), but we could work on it a bit.

Tell me something.

**Comment by luisgoncalves** [comment]
Nothing against it. But you choose it :)

**Comment by jzeferino** [comment]
@luisgoncalves what do you like more:

1:
![final](https://cloud.githubusercontent.com/assets/10722952/24322035/bff67630-1153-11e7-9dfa-49206ada5954.png)

2:
![final2](https://cloud.githubusercontent.com/assets/10722952/24322036/c23521c6-1153-11e7-9fb6-385ade26dacc.png)

3: None.

**Comment by luisgoncalves** [comment]
Number 1.

**Comment by luisgoncalves** [comment]
I've added more content. Please validate.

- Should we remove references to the core and mobile packages for now?
- Is there any content for "remarks"?

**Comment by jzeferino** [comment]
Good job.
* Regarding the references, should we just create the nuget packages and upload them? Or you think ins't necessary and just strip them from the readme.
* We talked about the remarks a fews weeks ago, if I remember well, we discussed the fact that the we don't support localization nesting as we seen in _some javascript library_.

**Comment by luisgoncalves** [comment]
- I was thinking about stripping them out, but since we describe the usage of Core, maybe we should create the packages. What do you think about having 2 more packages: `ResxConverter.Core` and `ResxConverter.CLI`?
- True. I'll add that note.

**Comment by jzeferino** [comment]
The `ResxConverter.Core` was already in the readme and I thinks it good to have it there. Yes we could have the `CLI`

anyway, we will have 4 packages. `Core, Cake, Mobile, and CLI`. 
**Are we overcomplicating this?**

**Comment by luisgoncalves** [comment]
I wasn't considering the `Mobile` package. My idea is:

- `ResxConverter.Core` - The core classes/interfaces for expansion
- `ResxConverter.CLI` - All the available converters, used from CLI
- `Cake.ResxConverter` - All the available converters, used from Cake

I think that anyone using this will either be on Cake or any other build system where the CLI is the most flexible option.

**Comment by jzeferino** [comment]
Ok it makes sense. The only thing that I don't really like is if for some reason you want to use the `ResxConverter` in the msbuild via target file, we would have to call the `.exe` with `mono` to call it.

**Comment by luisgoncalves** [comment]
Uhm... true. We can just stick with Cake for now if you prefer.

**Comment by jzeferino** [comment]
I've been thinking a bit on this topic. Lets have, Core, Cake and CLI as packages. My only fear is that the readme stays to big or hard to understand due to so many packages. But only the Cake package is kinda limited.

**Comment by luisgoncalves** [comment]
I'll replace "usage from code" with "usage from CLI".

**Comment by jzeferino** [comment]
Since we support nested resource files within folder passed as argument, I will remove the REMARKS.
