### ISSUE TITLE
Add Cake addin

### ISSUE THREAD

**Issue by luisgoncalves** [jzeferino/ResxConverter#18]
- http://cakebuild.net/docs/fundamentals/aliases
- https://github.com/cake-contrib/Cake.Webpack
- https://github.com/cake-contrib/Cake.Http/blob/develop/src/Cake.Http/HttpClientAliases.cs

**Comment by luisgoncalves** [comment]
@jzeferino take a look at the initial commit for this, please

**Comment by jzeferino** [comment]
I'm on very low quality internet and time. The resx provider should be called resx mobile provider?

**Comment by luisgoncalves** [comment]
The idea was that the class would contain all the conversion methods, current and future.

**Comment by luisgoncalves** [comment]
Last commit finished this. I think it's ready to generate the NuGet package.

**Comment by jzeferino** [comment]
From the

**Comment by luisgoncalves** [comment]
I've updated `run.cake` to use the add-in package. Looks good.

`.\build.ps1 -Script .\run.cake`

**Comment by jzeferino** [comment]
Cool.
