### ISSUE TITLE
Add and publish Core and CLI nugets

### ISSUE THREAD

**Issue by jzeferino** [jzeferino/ResxConverter#20]
I've done the creation of the nuspec and cake script for the new packages.
Please take a look at the nuspecs.

Since we have 3 nuget packages, we will have to deal with version maintence in the Cake script.
For now I just added the package creation with the same version as Cake.

**Comment by jzeferino** [comment]
I've merged develop with master to test if the readme icon and nugets icon worked.
If you have time please test the Core and CLI packages.

**Comment by luisgoncalves** [comment]
- You could have changed the default branch on the repository settings to "develop" =P
- I have those warnings from the start on my local machine

**Comment by luisgoncalves** [comment]
I've changed the CLI package to include the binaries on `tools` instead of `lib`. Having them on `lib` would cause the exe to be added as reference if the package installed in a project.

**Comment by jzeferino** [comment]
Did you republish the nugets?
What about versioning?

**Comment by luisgoncalves** [comment]
- I didn't republish because I'd need to set the environment variable for AppVeyor. Can you republish? alpha2 or beta1?
- I'll think a bit more about this.
- Yes. I don't know exactly why... But I guess it's not a problem.

**Comment by jzeferino** [comment]
Regarding the AppVeyor environment variables, I've  the packages from my local machine with hardcoded version.

**Comment by jzeferino** [comment]
What's the final decision on this?

**Comment by luisgoncalves** [comment]
What if we just finish and publish it as it is? We put the version on `build.cake` and maybe push the package from the appveyor build (`develop` -> prerelease version; `master` -> release version).

We'll think about splitting into different repos and other versioning issues when updates are required.

**Comment by jzeferino** [comment]
So, for now, we will need to configure Appveyor to push the releases? All with the same version?

**Comment by luisgoncalves** [comment]
I think so. Update build.cake to do that. Do you agree? Maybe I can try to do it later on.

**Comment by luisgoncalves** [comment]
@jzeferino looks good.

https://ci.appveyor.com/project/jzeferino/resxconverter

**Comment by jzeferino** [comment]
Yes, it's ok! 
I will remove the:

```
    <dependencies>
      <group targetFramework="net45" />
    </dependencies>
```

from the Core and Cake nuspec. 
Then I guess its time for the v1.0.0.
