### ISSUE TITLE
Prepare for first release

### ISSUE THREAD

**Issue by jzeferino** [jzeferino/ResxConverter#21]
Guess its time to make it!
Are we good to release all the packages for the 1.0.0?

**Important note**
We should update the readme based on the new release packages (eg: examples.)

**Comment by luisgoncalves** [comment]
I think it's ready. Take a look at my commits and merge to master if it's ok.

https://ci.appveyor.com/project/jzeferino/resxconverter/build/1.0.0-pre41

**Comment by luisgoncalves** [comment]
We should find a way to publicize this. Maybe on .NET weekly? Should we have a blog post or a complete application example?

**Comment by jzeferino** [comment]
Thats a good idea. We should have both. I can do the application, but I would like to have something calling the ResxConverter from the IDE. Regarding the blog post, it is really needed for .NET weekly posting?

**Comment by luisgoncalves** [comment]
Cool. Maybe it should be done in a separate repo/solution, because it will require Xamarin. 

I don't think the blog post is required. We probably can just link the project and the sample application. Maybe we should add something about the Xamarin use-case to the readme.

**Comment by jzeferino** [comment]
I agree with the use-case in readme. Any idea to make ResxConverter run from IDE without a TASK or before build msbuild directive?

**Comment by luisgoncalves** [comment]
In VS I have this option:

![image](https://cloud.githubusercontent.com/assets/3973253/24976594/5f924a64-1fca-11e7-98f4-167864465a01.png)

Which adds the following to the csproj:

![image](https://cloud.githubusercontent.com/assets/3973253/24976626/8123421e-1fca-11e7-955b-dc72a169e4d3.png)

**Comment by luisgoncalves** [comment]
Regarding the readme, what do you think of after this:

> Both the Cake and CLI packages include all the available converters, namely support for conversion to iOS and Android resource files.

Adding this:

One of the intended use-cases is the conversion of resx files to native resource files in Xamarin projects.

**Comment by jzeferino** [comment]
That change in readme looks good to me but would be cool to reference the sample project. I Will do that in the weekend.

Regarding the `PrebuildEvent` or a `Task` or `Target` to do that, its ok, but was looking on another way to do it. One that comes out of the box when installed the package for example. Something that don't force the user to handle csprojects manually. 
We could make the nuget add that msbuild property when installed. 

Do you think is too much specific?
