### ISSUE TITLE
string name parsing

### ISSUE THREAD

**Issue by jzeferino** [jzeferino/ResxConverter#23]
When parsing `ThisIsASampleString` the generated outpu is: `this_is_asample_string`.

**Comment by luisgoncalves** [comment]
I have one regex from another project that I think handles these cases better. It was taken from SO and it is far more complicated, with lookaheads and stuff:

`               (?<!^) # Not start
                (
                    # Digit, not preceded by another digit
                    (?<!\d)\d 
                    |
                    # Upper-case letter, followed by lower-case letter if
                    # preceded by another upper-case letter, e.g. 'G' in HTMLGuide
                    (?(?<=[A-Z])[A-Z](?=[a-z])|[A-Z])
                )`

It does the job, though, and I couldn't come up with a simpler one.

Can you come up with anything else?

**Comment by luisgoncalves** [comment]
@jzeferino I made a version based on the aforementioned regex. If you're ok with it, close this issue.

**Comment by jzeferino** [comment]
Yep, im ok with it. Tryed other regex but no success. Good to me. Btw im dealing with the cake addin publish in cake website right now.
