### ISSUE TITLE
Add Cake.ResxConverter to cake contrib

### ISSUE THREAD

**Issue by jzeferino** [jzeferino/ResxConverter#24]
If it makes sense.

**Comment by luisgoncalves** [comment]
Yep. We should start by separating this project into a dedicated repository, as we had discussed.

**Comment by jzeferino** [comment]
@luisgoncalves Did the separation, please when you have time, review the readmes. I could have done some shit.
Will open a new issue in [Cake.ResxConverter](https://github.com/jzeferino/Cake.ResxConverter/) to make the contrib for cake.

**Comment by luisgoncalves** [comment]
👍
