### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by jzeferino** [jzeferino/ResxConverter#5]
After conversion some strings get encoded in the xml.
Need to check if it will affect applications.

**Comment by jzeferino** [comment]
Did some local tests, but need to do more experiences, and discussion with @luisgoncalves.

**Comment by luisgoncalves** [comment]
@jzeferino please test this on your system and close the issue if it is OK.

**Comment by jzeferino** [comment]
We're good.

for:

```
data name="stringen" xml:space="preserve">
    <value>Co"uld" not sa\\ve the gam//e
content.</value>
  </data>
```

we got:

`"stringen" = "Co\"uld\" not sa\\\\ve the gam//e\ncontent.";
`

on the device:

![screen shot 2017-03-07 at 23 30 05](https://cloud.githubusercontent.com/assets/10722952/23682922/085289e2-038e-11e7-98e2-8d5c6503646f.png)

I've updated above the information for the escaped strings on ios and android with the urls were I toke it.

I've also found a important bug related with the names of the generated folders. Fixed in 5e5f012 and c42c6dc.

**Comment by jzeferino** [comment]
So, from the tests I made, the:

```
data name="stringen" xml:space="preserve">
    <value>Co"uld" not sa\\ve the gam//e
content.</value>
  </data>
```

gots converted into:

```
	<string name="stringen">Co"uld" not sa\\ve the gam//e
content.</string>
```

and this prints:

![screen shot 2017-03-25 at 11 50 43](https://cloud.githubusercontent.com/assets/10722952/24321935/5195e772-1151-11e7-9549-f71f7e75912e.png)

To make it look correct I've escaped the " and the \ and the \n and it worked:

For "stringen" = "Co\"uld\" not sa\\\\ve the gam//e\ncontent.";

the output was:

![screen shot 2017-03-25 at 11 53 04](https://cloud.githubusercontent.com/assets/10722952/24321943/9fde7638-1151-11e7-9b72-f05820161dbc.png)

From more experiences and from reading the a https://github.com/jzeferino/ResxConverter/issues/5#issuecomment-280945234

the ' must be escaped on android, but on ios its good.

So, to wrap up, we must escape " and the \ and the \n has we did on ios, plus we have to escape ' in android.

Let me hear from you @luisgoncalves .

**Comment by luisgoncalves** [comment]
From your two comments I understood that, in Android, if the whole string is wrapped in quotes in the `strings.xml` file, escape characters are not processed. Is this correct? If so, wouldn't it be enough to just wrap the source string in quotes?

**Comment by jzeferino** [comment]
I guess the the first option won't work. I will need to test, because if we have for example "bad "string"" this won't work. the " must be encoded. Will try it.

Guess we will go for the second option, but my questions is, since we are already escaping the characters in ios, we should refactor that code a re-use that code in android two. adding a condition in Android to encode '.

**Comment by luisgoncalves** [comment]
> For "stringen" = "Co"uld" not sa\\ve the gam//e\ncontent.";

In that example you gave, it seems to be OK. And on comment number 5 also:

```
<string name="good_example">This\'ll work</string>
<string name="good_example_2">"This'll also work"</string>
```

The start/end double-quotes seem to avoid the escape.

**Comment by jzeferino** [comment]
I've been testing this but we have problem even wrapping the string inside "".
So, for the string:

	<string name="stringen">"Co"uld" not sa\\ve the g'am//ec
ontent."</string>

we've got: 
![screen shot 2017-03-29 at 09 13 20](https://cloud.githubusercontent.com/assets/10722952/24444901/fbbf697e-145f-11e7-8f19-2ba0af4ff985.png)

So the new line worked well but the Co"uld" got wrong.

I guess in this case we should parse as we do it in ios, plus adding a special case for the ' character.

what do you think?

**Comment by luisgoncalves** [comment]
So the quotes are always stripped. Lets go with the "individual" escaping, similar to iOS. I'll do it today.

**Comment by luisgoncalves** [comment]
Test this again when you have a chance.
