### ISSUE TITLE
Add appveyor

### ISSUE THREAD

**Issue by jzeferino** [jzeferino/ResxConverter#9]

**Comment by jzeferino** [comment]
@luisgoncalves the string interpolation is supported on osx but, not supported on windows (tested on my windows VM).

**Comment by luisgoncalves** [comment]
They had a -Experimental switch to enable roslyn.. But I thought roslyn was
the default already..

**Comment by jzeferino** [comment]
Should I create a new issue for we to try the experimental parameter?
